stages:
  - build-container
  - deploy

variables:
  OKTETO_REGISTRY: registry.cloud.okteto.net
  OKTETO_IMAGE_TAG: $OKTETO_REGISTRY/$CI_PROJECT_PATH
  SED_OKTETO_IMAGE_TAG: "registry.cloud.okteto.net\/cjtim\/bsc-portfolio"
  TAG: $CI_COMMIT_SHORT_SHA
  # For dind
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build-container-okteto:
  stage: build-container
  image: docker:19
  services:
    - docker:19-dind
  script:
    - docker login -u cjtim -p $(echo $OKTETO_TOKEN | base64 -d) $OKTETO_REGISTRY
    - docker build -t $OKTETO_IMAGE_TAG:$TAG -f Dockerfile .
    - docker push $OKTETO_IMAGE_TAG:$TAG
    - docker logout $OKTETO_REGISTRY
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_COMMIT_BRANCH =~ /^(test)+/"

okteto:
  stage: deploy
  needs:
    - build-container-okteto
  image: okteto/okteto:1.13.4
  script:
    - export OKTETO_TOKEN=$(echo $OKTETO_TOKEN | base64 -d)
    - okteto namespace
    - |
      sed -e "s/TAG/$TAG/" k8s/deployment.yaml \
      | sed -e "s/IMAGE/$SED_OKTETO_IMAGE_TAG/" \
      | kubectl apply -f -
    - kubectl apply -f k8s/service.yaml
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_COMMIT_BRANCH =~ /^(test)+/"
